INSERT INTO libros (titulo, autor, editorial, numero_paginas, prestado,foto) VALUES ('Harry Potter y la Piedra Filosofal', 'JK.Rowling', 'Anaya', 345, false,'');
INSERT INTO libros (titulo, autor, editorial, numero_paginas, prestado,foto) VALUES ('1984', 'George Orwell', 'Debolsillo', 368, false,'');
INSERT INTO libros (titulo, autor, editorial, numero_paginas, prestado,foto) VALUES ('Cien años de soledad', 'Gabriel García Márquez', 'Diana', 471, false,'');
INSERT INTO libros (titulo, autor, editorial, numero_paginas, prestado,foto) VALUES ('El Gran Gatsby', 'F. Scott Fitzgerald', 'DeBolsillo', 216, false,'');
INSERT INTO libros (titulo, autor, editorial, numero_paginas, prestado,foto) VALUES ('Don Quijote de la Mancha', 'Miguel de Cervantes', 'Real Academia Española', 992, false,'');
INSERT INTO libros (titulo, autor, editorial, numero_paginas, prestado,foto) VALUES ('Orgullo y prejuicio', 'Jane Austen', 'Alba Editorial', 440, false,'');
INSERT INTO libros (titulo, autor, editorial, numero_paginas, prestado,foto) VALUES ('El señor de los anillos', 'J.R.R. Tolkien', 'Minotauro', 1216, false,'');
INSERT INTO libros (titulo, autor, editorial, numero_paginas, prestado,foto) VALUES ('Matar a un ruiseñor', 'Harper Lee', 'Grasset', 376, false,'');   
INSERT INTO libros (titulo, autor, editorial, numero_paginas, prestado,foto) VALUES ('Crimen y castigo', 'Fyodor Dostoyevsky', 'Editorial Eneida', 672, false,'');  
INSERT INTO libros (titulo, autor, editorial, numero_paginas, prestado,foto) VALUES ('El Principito', 'Antoine de Saint', 'Salamandra', 96, false,'');  
INSERT INTO libros (titulo, autor, editorial, numero_paginas, prestado,foto) VALUES ('Los juegos del hambre', 'Suzanne Collins', 'Salamandra', 416, false,'');
INSERT INTO libros (titulo, autor, editorial, numero_paginas, prestado,foto) VALUES  ('Cazadores de sombras: Ciudad de hueso', 'Cassandra Clare', 'Salamandra', 504, false,'');
INSERT INTO libros (titulo, autor, editorial, numero_paginas, prestado,foto) VALUES  ('El código Da Vinci', 'Dan Brown', 'Salamandra', 624, false,'');
INSERT INTO libros (titulo, autor, editorial, numero_paginas, prestado,foto) VALUES  ('El alquimista', 'Paulo Coelho', 'Salamandra', 208, false,''); 
INSERT INTO libros (titulo, autor, editorial, numero_paginas, prestado,foto) VALUES ('El señor de los anillos: La comunidad del anillo', 'J.R.R. Tolkien', 'Minotauro', 512, false,'');
INSERT INTO libros (titulo, autor, editorial, numero_paginas, prestado,foto) VALUES ('El señor de los anillos: Las dos torres', 'J.R.R. Tolkien', 'Minotauro', 448, false,'');
INSERT INTO libros (titulo, autor, editorial, numero_paginas, prestado,foto) VALUES ('El señor de los anillos: El retorno del rey', 'J.R.R. Tolkien', 'Minotauro', 512, false,'');
INSERT INTO libros (titulo, autor, editorial, numero_paginas, prestado,foto) VALUES ('El hobbit', 'J.R.R. Tolkien', 'Minotauro', 320, false,'');   
